{% set version = "1.3.14" %}
{% set buildnumber = 0 %}

package:
    name: mkl_fft
    version: {{ version }}

source:
    path: ../

build:
    number: {{ buildnumber }}
    ignore_run_exports:
      - blas

requirements:
    build:
      - {{ compiler('c') }}
    host:
      - python
      - setuptools >=77
      - mkl-devel
      - cython
      - numpy
    run:
      - python
      - mkl-service
      - numpy
      - scipy >=1.10.1

test:
    commands:
      - pytest -v --pyargs mkl_fft
    requires:
      - pytest
    imports:
      - mkl_fft
      - mkl_fft.interfaces
      - mkl_fft.interfaces.numpy_fft
      - mkl_fft.interfaces.scipy_fft

about:
    home: http://github.com/IntelPython/mkl_fft
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel® oneAPI Math Kernel Library (OneMKL)
