{% set version = "1.0dev" %}
{% set buildnumber = 0 %}


package:
    name: mkl_fft
    version: {{ version }}

source:
    path: ../

build:
    number: {{buildnumber}}
    features:
      - intel
    always_include_files:
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/__init__.py
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/_float16_utils.py
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/_pydfti.*
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/_numpy_fft.py
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/_scipy_fft.py
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/setup.py
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/tests/test_fft1d.py
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/__init__.pyc         [py27]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/_float16_utils.pyc   [py27]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/_numpy_fft.pyc       [py27]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/_scipy_fft.pyc       [py27]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/setup.pyc            [py27]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/tests/test_fft1d.pyc [py27]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/__pycache__/*        [py3k]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/tests/__pycache__/*  [py3k]
      - {{ SP_DIR.replace('\\', '/') if win else SP_DIR }}/mkl_fft/

requirements:
    build:
      - python
      - setuptools
      - intelpython
      - mkl-devel               [not nomkl]
      - cython
      - numpy x.x
    run:
      - python
      - mkl                     [not nomkl]
      - intelpython
      - numpy x.x

test:
    commands:
      - nosetests -v mkl_fft
    requires:
      - nose
    imports:
      - mkl_fft
      - mkl_fft._numpy_fft
      - mkl_fft._scipy_fft

about:
    home: http://github.com/IntelPython/mkl_fft
    license: BSD
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library
