{% set version = "2.1.0dev0" %}
{% set buildnumber = 0 %}

package:
    name: mkl_fft
    version: {{ version }}

source:
    path: ../

build:
    number: {{ buildnumber }}
    script_env:
      - WHEELS_OUTPUT_FOLDER
    ignore_run_exports:
      - blas

requirements:
    build:
      - {{ compiler('c') }}
      - {{ stdlib('c') }}
    host:
      - python
      - pip
      - setuptools >=77
      - mkl-devel
      - cython
      - numpy-base
      - wheel  >=0.41.3
    run:
      - python
      - mkl-service
      - {{ pin_compatible('numpy-base') }}

test:
    commands:
      - pytest -v --pyargs mkl_fft
    requires:
      - pytest
      - scipy >=1.10
    imports:
      - mkl_fft
      - mkl_fft.interfaces
      - mkl_fft.interfaces.numpy_fft
      - mkl_fft.interfaces.scipy_fft

about:
    home: http://github.com/IntelPython/mkl_fft
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel® oneAPI Math Kernel Library (OneMKL)
