# Intel numpy-base is still needed for internal wheels CI, so we control its use with this optional toggle
{% set use_numpy_base = environ.get('USE_NUMPY_BASE', 'true').lower() == 'true' %}

package:
    name: mkl_fft
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ../

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script_env:
      - WHEELS_OUTPUT_FOLDER
    ignore_run_exports:
      - blas
      {% if use_numpy_base %}
      - numpy-base
      {% else %}
      - numpy
      {% endif %}

requirements:
    build:
      - {{ compiler('c') }}
      - {{ stdlib('c') }}
    host:
      - python
      - python-gil     # [py>=314]
      - pip
      - setuptools >=77
      - mkl-devel
      - cython
      {% if use_numpy_base %}
      - numpy-base
      {% else %}
      - numpy
      {% endif %}
      - wheel  >=0.41.3
    run:
      - python
      - python-gil     # [py>=314]
      - {{ pin_compatible('mkl') }}
      {% if use_numpy_base %}
      - numpy-base
      {% else %}
      - numpy >=1.26.4
      {% endif %}

test:
    commands:
      - pytest -v --pyargs mkl_fft
    requires:
      - pytest
      - scipy >=1.10
      - mkl-service
    imports:
      - mkl_fft
      - mkl_fft.interfaces

about:
    home: http://github.com/IntelPython/mkl_fft
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel® oneAPI Math Kernel Library (oneMKL)
    description: |
        <strong>LEGAL NOTICE: Use of this software package is subject to the
        software license agreement (as set forth above, in the license section of
        the installed Conda package and/or the README file) and all notices,
        disclaimers or license terms for third party or open source software
        included in or with the software.</strong>
        <br/><br/>
        EULA: <a href="https://opensource.org/licenses/BSD-3-Clause" target="_blank">BSD-3-Clause</a>
        <br/><br/>
